### PR TITLE
install folder changed to correct one in insall script

### PR DESCRIPTION
**Pull request by 6r15u**
documentation on install folder corrected

### CODE REVIEW

**Comment by 6r15u** [comment]
@thopiekar How is it possible to get into the team for openhab-qnap-qpkg.
I could help managing the issues and if i further study the qpkg creation also in the features for that package

**Comment by thopiekar** [comment]
Of course. At the moment the situation is, that there is nobody, who is going to maintain and continue working on the QPKG officially here.
I don't own a QNAP product anymore, but still felt responsible for this project as long as there was nobody else.

I will care about getting you into the team and giving you permissions to work here!

Welcome!

**Comment by 6r15u** [comment]
Ok, thanks, I'll give my best to keep the QPKG package updated, but it'll need some time until I understand everything you already did.

**Comment by thopiekar** [comment]
No problem. Take your time and if you are unsure, just ask!
Also if you like I can take a look on your PRs and we can discuss.

Good luck!

**Pull request merged**
