### PR TITLE
Fixed openHAB configuration path

### PR DESCRIPTION
**Pull request by tomquist**
Actually instead of "openHAB2" the share the installation script is looking for is called "openHAB"

### CODE REVIEW

**Comment by thopiekar** [comment]
Hey @tomquist 
many thanks for your PR. There are rules by the OpenHAB maintainers, that every comm+it message ends with eg.:
`Signed-off-by: Thomas Karl Pietrowski <thopiekar@gmail.com> (github: thopiekar)`
That's why I can't merge this PR. Could you be so kind and make a new PR?

**Comment by kaikreuzer** [comment]
@thopiekar I think this PR can be considered for the [small patch exception](https://github.com/openhab/openhab-qnap-qpkg/blob/master/CONTRIBUTING.md#small-patch-exception).

In general, there is no need for new PRs if sign-offs are missing - the branch can simply be updated (squashed) and force pushed, so that the PR afterwards contains the correct sign-off footers.

> OpenHAB maintainers

It's "openHAB" ;-)

**Comment by thopiekar** [comment]
Good morning @kaikreuzer 

oh, ok, but it depends whether the owner of the commits wants to squash them up. But yes, you are right this can be done like that every quickly.

Haha, sorry, it is still too early :see_no_evil:

**Comment by tomquist** [comment]
Hey @thopiekar,
I changed my PR accordingly.

**Comment by thopiekar** [comment]
Hmm, well, but the idea is that you add your details in there.
However, I'll merge it now.

Thanks again :wink:

**Comment by tomquist** [comment]
Ok, sorry for the confusion, I misinterpreted it as a kind of review process without looking into contribution rules. Tbh I don't understand the point in adding my own data there as it is already part of the commit metadata.

**Pull request merged**
