### PR TITLE
set timezone depending on system timezone

### LINKED ISSUE #8: timezone is not set
Hi.
I'm from Germany and we have winter time, now. But in OpenHAB there is shown the old summer time. NTP ist working well and my QNAP NAS is working with the correct winter time, too. 

I found the solution for this. It is necessary to add the following line to openHAB.sh:
export TZ=`/sbin/getcfg System "Time Zone" -f /etc/config/uLinux.conf`

It's working fine in my case.

Regards.
Andy

### PR DESCRIPTION
**Pull request by Andy1402**
Please see the issue. Without this line OpenHAB will work with summer time instead of winter time.

Fixes #8

### CODE REVIEW

**Comment by thopiekar** [comment]
Sounds good. Returns `Europe/Amsterdam` here.

Is there a way to see which timezone is currently used by OH2?

Thanks!

**Comment by Andy1402** [comment]
I'm not sure if you can see the timezone in OH2 directly. But without this I see the wrong time in the log files. Furthermore I added the NTP thing and the following item:
DateTime HeuteJetzt  "Heutiges Datum [%1$tA, %1$td.%1$tm.%1$tY, %1$tT]" <calendar> { channel="ntp:ntp:local:dateTime" }

In the sitemap I added the item:
Text item=HeuteJetzt

In my sitemap is the same time shown as in the log files. Now, with this fix, it is the correct time.

**Comment by thopiekar** [comment]
Ok, good argument. I would merge this directly into the repository, but there is a little problem: Your commit misses a `Signed-Off` tag.

The maintainers of OH want these tags in the end of every commit message. For example the last one here: https://github.com/openhab/openhab-qnap-qpkg/commit/6280e181661da3f1d8908416820f55a8bf59118d

Could you be so kind any recreate this PR including the tag?

Thanks!

**Comment by Andy1402** [comment]
Sorry, I didn't get it. Which Signed-Off tag do you mean?
I have seen the command line in other forums and it was included in my old qpkg for OH1.8.3, too. It is a part from the start procedure. In each case there was exactly this line without further tags. I'm not sure what you are missing exactly.

**Comment by thopiekar** [comment]
Do you see the last line in my commit message? Which starts with `Signed-Off:`?
I exactly need this in your commit, too.

**Comment by thopiekar** [comment]
Haha, doch nicht so. Ich erledige das in Kürze für dich :wink:

**Comment by Andy1402** [comment]
Hehe sorry that is my first time. I wrote in the code, first. Now it the Signed-Off-Tag is in the comment. Is it correct, now? :-)

**Comment by thopiekar** [comment]
Well, your PR now includes also commits with messages which are not valid (Without a Signed-Off: tag).
I'll add your change now directly to the master branch and mention + thank you for your work in this commit of course!

**Comment by thopiekar** [comment]
I hope you are fine with that :smiley:

**Comment by Andy1402** [comment]
Yupp, thank you ^^

**Pull request closed without merging**
